# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default="I'm a description!", max_length=250)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
