# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20170527_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerinstance',
            name='form',
        ),
        migrations.RemoveField(
            model_name='answerinstance',
            name='question',
        ),
        migrations.AddField(
            model_name='filledform',
            name='data',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Short_answer', 'Short-answer'), ('Paragraph', 'long-answer'), ('Integer', 'Integer-answer'), ('ChoiceField', 'Choice'), ('MultipleChoiceField', 'Multiple-choice')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AnswerInstance',
        ),
    ]
