# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20170528_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_choices',
            field=models.TextField(blank=True, help_text='make new line for new option', max_length=600, null=True),
        ),
    ]
