# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20170613_2229'),
        ('forms', '0006_auto_20170613_1626'),
    ]

    operations = [
    ]
