# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_merge_20170614_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='description',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='status',
        ),
    ]
