# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtag',
            name='tag_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
