# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominationinstance',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='nominationinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Accepted'), ('r', 'Rejected')], default=None, max_length=1, null=True),
        ),
    ]
