# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-26 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomi', '0003_nomination_results_declared'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('programme', models.CharField(choices=[('bt', 'B.Tech'), ('bs', 'B.S')], default='bt', max_length=4)),
                ('department', models.CharField(choices=[('Aerospace Engineering', 'AE'), ('Biological Sciences and Engineering', 'BSBE')], default=None, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
