# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-26 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('Aerospace Engineering', 'AE'), ('Biological Sciences and Engineering', 'BSBE')], default=None, max_length=200),
        ),
    ]
