# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0009_auto_20170526_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hall',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('Y16', 'Y16'), ('Y15', 'Y15'), ('Y14', 'Y14'), ('Y13', 'Y13'), ('Y12', 'Y12'), ('Y11', 'Y11')], default='Y16', max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('Aerospace Engineering', 'AE'), ('Biological Sciences & Engineering', 'BSBE'), ('Chemical Engineering', 'CHE'), ('Civil Engineering', 'CE'), ('Computer Science & Engineering', 'CSE'), ('Electrical Engineering', 'EE'), ('Materials Science & Engineering', 'MSE'), ('Mechanical Engineering', 'ME'), ('Industrial & Management Engineering', 'IME'), ('Chemistry', 'CHM'), ('Mathematics & Scientific Computing', 'MTH'), ('Physics', 'PHY'), ('Earth Sciences', 'ES')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
    ]
