# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0010_auto_20170526_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hall',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1),
        ),
    ]
