# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0012_auto_20170526_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='programme',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.S', 'B.S')], default='B.Tech', max_length=7),
        ),
    ]
