# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20170527_0937'),
        ('nomi', '0014_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='nomi_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='post',
            name='persons',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
