# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20170527_0937'),
        ('nomi', '0019_auto_20170527_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationinstance',
            name='filled_form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.FilledForm'),
        ),
    ]
