# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0022_auto_20170529_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approvals',
            field=models.ManyToManyField(blank=True, related_name='_post_approvals_+', to='nomi.Post'),
        ),
    ]
