# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-29 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0023_post_approvals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, null=True)),
                ('club_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomi.Club')),
            ],
        ),
    ]
