# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-29 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0025_post_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nomi.Club'),
        ),
        migrations.AlterField(
            model_name='post',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomi.Club'),
        ),
    ]
