# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-30 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0027_auto_20170530_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='club_nomi',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomi.Club'),
        ),
    ]
