# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-30 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomi', '0028_nomination_club_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
