# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0030_remove_nomination_club_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Nomination created', 'Nomination created'), ('Nomination out', 'Nomination out'), ('Interview period', 'Interview period'), ('Assigned', 'Assigned')], default='Nomination created', max_length=50),
        ),
    ]
