# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0031_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nomination',
        ),
        migrations.AddField(
            model_name='nomination',
            name='nomi_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nomi.Post'),
        ),
    ]
