# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0032_auto_20170604_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approvals',
        ),
        migrations.AddField(
            model_name='nomination',
            name='status',
            field=models.CharField(choices=[('Nomination created', 'Nomination created'), ('Nomination out', 'Nomination out'), ('Interview period', 'Interview period'), ('Compiled', 'Compiled')], default='Nomination created', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='post_approvals',
            field=models.ManyToManyField(blank=True, related_name='_post_post_approvals_+', to='nomi.Post'),
        ),
    ]
