# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0033_auto_20170604_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_approvals',
            field=models.ManyToManyField(blank=True, related_name='approvals', to='nomi.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Nomination created', 'Nomination created'), ('Nomination out', 'Nomination out'), ('Assigned', 'Assigned')], default='Nomination created', max_length=50),
        ),
    ]
