# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0035_auto_20170605_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Post created', 'Post created'), ('Approved', 'Approved'), ('rejected', 'rejected'), ('Assigned', 'Assigned')], default='Nomination created', max_length=50),
        ),
    ]
