# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-05 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0037_auto_20170605_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominationChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Nomination created', 'Nomination created'), ('Nomination out', 'Nomination out'), ('Interview period', 'Interview period'), ('Compiled', 'Compiled')], default='Post created', max_length=50),
        ),
    ]
