# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0042_auto_20170606_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='perms',
            field=models.CharField(choices=[('normal', 'normal'), ('can approve the post', 'can approve the post'), ('can send nominations to users', 'can send nominations to users')], default='normal', max_length=200),
        ),
    ]
