# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0043_post_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='perms',
            field=models.CharField(choices=[('normal', 'normal'), ('can approve the post', 'can approve the post'), ('can approve post and send nominations to users', 'can approve post and send nominations to users')], default='normal', max_length=200),
        ),
    ]
