# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0045_remove_nomination_results_declared'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='nomi_approvals',
            field=models.ManyToManyField(blank=True, related_name='nomi_approvals', to='nomi.Post'),
        ),
    ]
