# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0046_nomination_nomi_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominationinstance',
            name='filled_form',
        ),
        migrations.AddField(
            model_name='nominationinstance',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
