# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20170528_0643'),
        ('nomi', '0047_auto_20170606_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationinstance',
            name='filled_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.FilledForm'),
        ),
    ]
