# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0048_nominationinstance_filled_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_approvals',
            field=models.ManyToManyField(blank=True, related_name='approvals', to='nomi.Club'),
        ),
        migrations.AddField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('Post created', 'Post created'), ('Post approved', 'Post approved'), ('Post rejected', 'Post rejected'), ('Post on work', 'Post on work')], default='Club created', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Club created', 'Club created'), ('Club approved', 'Club approved'), ('Club rejected', 'Club rejected'), ('Club on work', 'Club on work')], default='Post created', max_length=50),
        ),
    ]
