# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-07 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0049_auto_20170607_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='perms',
            field=models.CharField(choices=[('normal', 'normal'), ('can approve the club', 'can approve the club'), ('can approve club and create posts within', 'can approve club and create posts within')], default='normal', max_length=200),
        ),
    ]
