# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0050_club_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('Club created', 'Club created'), ('Club approved', 'Club approved'), ('Club rejected', 'Club rejected'), ('Club on work', 'Club on work')], default='Club created', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Post created', 'Post created'), ('Post approved', 'Post approved'), ('Post rejected', 'Post rejected'), ('Post on work', 'Post on work')], default='Post created', max_length=50),
        ),
    ]
