# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0053_posthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthistory',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
