# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0054_auto_20170611_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
