# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0056_auto_20170613_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationinstance',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
