# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0057_auto_20170613_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationinstance',
            name='comments',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
