# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0058_auto_20170613_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='brief_desc',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name=models.TextField(blank=True, max_length=1000, null=True)),
        ),
    ]
