# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0060_auto_20170613_2237'),
        ('nomi', '0059_nomination_brief_desc'),
    ]

    operations = [
    ]
