# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0061_merge_20170614_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='brief_desc',
        ),
    ]
