# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0064_auto_20170614_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='description',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
