# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0065_auto_20170614_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='all_clubs',
            field=models.ManyToManyField(blank=True, related_name='all_club', to='nomi.Club'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='status',
            field=models.CharField(choices=[('Nomination created', 'Nomination created'), ('Nomination out', 'Nomination out'), ('Compiled', 'Compiled')], default='Nomination created', max_length=50),
        ),
    ]
