# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0066_auto_20170614_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='all_clubs',
        ),
        migrations.AddField(
            model_name='nomination',
            name='club_search',
            field=models.ManyToManyField(blank=True, related_name='all_clubs', to='nomi.Post'),
        ),
    ]
