# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0067_auto_20170614_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='status',
            field=models.CharField(choices=[('Nomination created', 'Nomination created'), ('Nomination out', 'Nomination out'), ('Interview period', 'Interview period'), ('Compiled', 'Compiled')], default='Nomination created', max_length=50),
        ),
    ]
