# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0068_auto_20170614_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
