# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0070_auto_20170614_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('Aerospace Engineering', 'AE'), ('Biological Sciences & Engineering', 'BSBE'), ('Chemical Engineering', 'CHE'), ('Civil Engineering', 'CE'), ('Computer Science & Engineering', 'CSE'), ('Electrical Engineering', 'EE'), ('Materials Science & Engineering', 'MSE'), ('Mechanical Engineering', 'ME'), ('Industrial & Management Engineering', 'IME'), ('Chemistry', 'CHM'), ('Mathematics & Scientific Computing', 'MTH'), ('Physics', 'PHY'), ('Earth Sciences', 'ES')], default='AE', max_length=200),
        ),
    ]
