# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0072_auto_20170614_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationinstance',
            name='interview_status',
            field=models.CharField(blank=True, choices=[('Interview Not Done', 'Interview Not Done'), ('Interview Done', 'Interview Done')], default='Interview Not Done', max_length=20, null=True),
        ),
    ]
