# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0073_nominationinstance_interview_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
