# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0076_auto_20170615_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_approvals',
        ),
        migrations.RemoveField(
            model_name='club',
            name='perms',
        ),
        migrations.RemoveField(
            model_name='club',
            name='status',
        ),
    ]
