# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomi', '0077_auto_20170618_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nominationinstance',
            name='comments',
        ),
        migrations.AddField(
            model_name='commment',
            name='nomi_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nomi.NominationInstance'),
        ),
        migrations.AddField(
            model_name='commment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
