# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0078_auto_20170619_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='result_approvals',
            field=models.ManyToManyField(blank=True, related_name='result_approvals', to='nomi.Post'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='status',
            field=models.CharField(choices=[('Nomination created', 'Nomination created'), ('Nomination out', 'Nomination out'), ('Interview period', 'Interview period'), ('Sent for ratification', 'Sent for ratification'), ('Work done', 'Work done')], default='Nomination created', max_length=50),
        ),
    ]
