# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0079_auto_20170622_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('nominations', models.ManyToManyField(blank=True, to='nomi.Nomination')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='perms',
            field=models.CharField(choices=[('normal', 'normal'), ('can ratify the post', 'can ratify the post'), ('can approve post and send nominations to users', 'can approve post and send nominations to users')], default='normal', max_length=200),
        ),
    ]
