# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0081_nomination_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnomination',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('out', 'out')], default='created', max_length=50),
        ),
    ]
