# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0082_groupnomination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnomination',
            name='approvals',
            field=models.ManyToManyField(blank=True, related_name='group_approvals', to='nomi.Post'),
        ),
    ]
