# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('nomi', '0083_groupnomination_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='tagname', to='info.ClubTag'),
        ),
    ]
