# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0085_auto_20170623_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='club',
            field=models.ManyToManyField(null=True, related_name='club_tags', to='info.ClubTag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post',
            field=models.ManyToManyField(null=True, related_name='user_post', to='nomi.Post'),
        ),
    ]
