# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0087_auto_20170623_1658'),
        ('nomi', '0085_auto_20170623_1707'),
    ]

    operations = [
    ]
