# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0088_merge_20170623_1740'),
        ('nomi', '0089_auto_20170623_1746'),
    ]

    operations = [
    ]
