# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0090_merge_20170623_1825'),
        ('nomi', '0090_merge_20170623_1823'),
    ]

    operations = [
    ]
