# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0091_merge_20170624_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_members',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_perms',
            field=models.CharField(choices=[('normal', 'normal'), ('Can create', 'Can create')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='club_posts', to='nomi.Club'),
        ),
    ]
