# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import nomi.models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0092_auto_20170624_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to=nomi.models.user_directory_path),
        ),
    ]
