# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0093_userprofile_user_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupnomination',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='groupnomination',
            name='club_search',
            field=models.ManyToManyField(blank=True, related_name='groups', to='nomi.Post'),
        ),
        migrations.AddField(
            model_name='groupnomination',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
