# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0095_post_club_search'),
        ('nomi', '0094_auto_20170624_1537'),
    ]

    operations = [
    ]
