# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0096_merge_20170624_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnomination',
            name='opening_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
