# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0097_auto_20170624_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnomination',
            name='opening_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 24, 19, 38, 40, 331552), null=True),
        ),
    ]
