# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 22:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0099_auto_20170624_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnomination',
            name='opening_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 24, 22, 27, 12, 175745, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_approvals',
            field=models.ManyToManyField(blank=True, null=True, related_name='approvals', to='nomi.Post'),
        ),
    ]
