# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0101_auto_20170624_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnomination',
            name='opening_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 25, 12, 5, 4, 587190, tzinfo=utc), null=True),
        ),
    ]
