# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0102_auto_20170625_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnomination',
            name='opening_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 25, 12, 18, 7, 961718, tzinfo=utc), null=True),
        ),
    ]
