# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0103_auto_20170625_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='club_search',
        ),
        migrations.AlterField(
            model_name='groupnomination',
            name='opening_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
