# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0104_auto_20170625_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
