# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0105_auto_20170625_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupnomination',
            name='club_search',
        ),
        migrations.AddField(
            model_name='groupnomination',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='club_group', to='nomi.Club'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='club_nomi', to='nomi.Club'),
        ),
    ]
