# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0108_auto_20170625_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='club_search',
        ),
    ]
