# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomi', '0110_auto_20170705_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='interview_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
