# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 10:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomi', '0111_nomination_interview_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='interview_panel',
        ),
        migrations.AddField(
            model_name='nomination',
            name='interview_panel',
            field=models.ManyToManyField(blank=True, related_name='panel', to=settings.AUTH_USER_MODEL),
        ),
    ]
