# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0112_auto_20170706_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
