# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0113_auto_20170712_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReopenNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reopening_date', models.DateField(blank=True, null=True)),
                ('approvals', models.ManyToManyField(null=True, to='nomi.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='nomination',
            name='status',
            field=models.CharField(choices=[('Nomination created', 'Nomination created'), ('Nomination out', 'Nomination out'), ('Interview period', 'Interview period'), ('Nomination reopened', 'Nomination reopened'), ('Sent for ratification', 'Sent for ratification'), ('Work done', 'Work done')], default='Nomination created', max_length=50),
        ),
        migrations.AlterField(
            model_name='nominationinstance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reopennomination',
            name='nomi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomi.Nomination'),
        ),
    ]
