# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0115_remove_commment_name_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthistory',
            name='session',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017)], default=2017),
        ),
    ]
