# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import nomi.models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0116_posthistory_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure', models.IntegerField(choices=[(2016, 2016), (2017, 2017)], default=2017, null=True)),
                ('end_date', models.DateField(default=nomi.models.default_end_date)),
            ],
        ),
        migrations.RemoveField(
            model_name='posthistory',
            name='session',
        ),
    ]
