# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0118_auto_20170805_1041'),
        ('nomi', '0115_auto_20170805_1059'),
    ]

    operations = [
    ]
