# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import nomi.models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0119_post_tenure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tenure',
            new_name='post_session',
        ),
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=nomi.models.default_end_date),
        ),
    ]
