# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0120_auto_20170805_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_session',
        ),
    ]
