# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0119_merge_20170805_1117'),
        ('nomi', '0122_auto_20170805_1217'),
    ]

    operations = [
    ]
