# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0123_merge_20170805_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reopennomination',
            name='approvals',
            field=models.ManyToManyField(to='nomi.Post'),
        ),
    ]
