# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0124_auto_20170805_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nomi_session',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017)], null=True),
        ),
    ]
