# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import nomi.models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0127_auto_20170806_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(default=nomi.models.default_end_date, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='tenure',
            field=models.IntegerField(blank=True, choices=[(2017, 2017), (2018, 2018)], default=2017, null=True),
        ),
    ]
