# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0129_auto_20170806_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_year',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
