# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0129_auto_20170805_1720'),
        ('nomi', '0131_auto_20170806_0641'),
    ]

    operations = [
    ]
