# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import nomi.models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0132_merge_20170806_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nomi_session',
            field=models.IntegerField(blank=True, choices=[(2017, 2017), (2018, 2018)], null=True),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='end',
            field=models.DateField(blank=True, default=nomi.models.default_end_date),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='post_tenure',
            field=models.IntegerField(choices=[(2017, 2017), (2018, 2018)], null=True),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='tenure',
            field=models.IntegerField(blank=True, choices=[(2017, 2017), (2018, 2018)], default=2017, null=True),
        ),
    ]
