# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0133_auto_20170806_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deratification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('status', models.BooleanField(default=False)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nomi.Post')),
            ],
        ),
    ]
