# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0132_auto_20170806_0940'),
        ('nomi', '0133_auto_20170806_0922'),
    ]

    operations = [
    ]
