# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0134_merge_20170806_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.RemoveField(
            model_name='posthistory',
            name='post_tenure',
        ),
        migrations.AddField(
            model_name='posthistory',
            name='post_session',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
