# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0135_auto_20170806_1015'),
        ('nomi', '0135_auto_20170806_1111'),
    ]

    operations = [
    ]
