# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0136_merge_20170807_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='post_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nomi.Session'),
        ),
    ]
