# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0136_merge_20170806_1143'),
        ('nomi', '0137_auto_20170809_1105'),
    ]

    operations = [
    ]
