# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0138_merge_20170809_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='elder_brother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elder', to='nomi.Post'),
        ),
    ]
