# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0140_post_last_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deratification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deratification',
            name='deratify_approvals',
        ),
        migrations.AddField(
            model_name='deratification',
            name='deratify_approvals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_deratify', to='nomi.Post'),
        ),
    ]
