# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0141_auto_20170811_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_approval',
        ),
        migrations.AddField(
            model_name='nomination',
            name='take_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='give_nomi_approval', to='nomi.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='take_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='give_approval', to='nomi.Post'),
        ),
    ]
