# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0142_auto_20170811_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='elder_brother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='little_bro', to='nomi.Post'),
        ),
    ]
