# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0143_auto_20170811_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deratification',
            old_name='deratify_approvals',
            new_name='deratify_approval',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='take_approval',
        ),
        migrations.AddField(
            model_name='deratification',
            name='status',
            field=models.CharField(choices=[('safe', 'safe'), ('requested', 'requested'), ('deratified', 'deratified')], default='safe', max_length=10),
        ),
    ]
