# -*- coding: utf-8 -*-
<<<<<<< HEAD
=======
# Generated by Django 1.11.2 on 2017-08-19 09:13
>>>>>>> 5fab31f556c8d7234c59811b7b407c9d2c51a360
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0144_auto_20170811_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
    ]
