# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.2 on 2017-08-19 09:10
=======
# Generated by Django 1.11.2 on 2017-08-19 09:13
>>>>>>> 56d47ff1692643d61f41ffcc9e7b1b741f9d8586
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0144_auto_20170811_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
    ]
