# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0145_remove_userprofile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationinstance',
            name='edit_time',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationinstance',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
