# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0146_auto_20170819_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, null=True)),
                ('club_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomi.ClubCreate')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_perms',
        ),
        migrations.AlterField(
            model_name='nominationinstance',
            name='edit_time',
            field=models.DateField(default=datetime.datetime(2017, 8, 19, 14, 51, 44, 327112), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Post created', 'Post created'), ('Post approved', 'Post approved')], default='Post created', max_length=50),
        ),
        migrations.AddField(
            model_name='clubcreate',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_request', to='nomi.Post'),
        ),
        migrations.AddField(
            model_name='clubcreate',
            name='take_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='give_club_approval', to='nomi.Post'),
        ),
    ]
