# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0146_auto_20170819_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationinstance',
            name='edit_time',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
