# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0147_auto_20170819_1451'),
        ('nomi', '0147_auto_20170820_0510'),
    ]

    operations = [
    ]
