# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0148_merge_20170820_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='dept_choice',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='hall_choice',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='year_choice',
        ),
        migrations.AlterField(
            model_name='clubcreate',
            name='club_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomi.Club'),
        ),
        migrations.AlterField(
            model_name='nominationinstance',
            name='edit_time',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
