# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0149_auto_20170822_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('Aerospace Engineering', 'AE'), ('Biological Sciences & Engineering', 'BSBE'), ('Chemical Engineering', 'CHE'), ('Civil Engineering', 'CE'), ('Computer Science & Engineering', 'CSE'), ('Electrical Engineering', 'EE'), ('Materials Science & Engineering', 'MSE'), ('Mechanical Engineering', 'ME'), ('Industrial & Management Engineering', 'IME'), ('Chemistry', 'CHM'), ('Mathematics & Scientific Computing', 'MTH'), ('Physics', 'PHY'), ('Earth Sciences', 'ES'), ('Cognitive Sciences', 'Cognitive Sciences'), ('Humanities and Social Sciences', 'HSS'), ('Laser Technology', 'Laser Technology'), ('Photonics Science & Engineering', 'Photonics Science & Engg.'), ('Statistics', 'Statistics')], default='AE', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='programme',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.S', 'B.S'), ('BS-MBA', 'BS-MBA'), ('BS-MS', 'BS-MS'), ('BS-MT', 'BS-MT'), ('BT-M.Des', 'BT-M.Des'), ('BT-MBA', 'BT-MBA'), ('BT-MS', 'BT-MS'), ('Exchng Prog.', 'Exchng Prog.'), ('MBA', 'MBA'), ('MDes', 'MDes'), ('MS-Research', 'MS-Research'), ('MSc(2 yr)', 'MSc(2 yr)'), ('MSc(Int)', 'MSc(Int)'), ('MT(Dual)', 'MT(Dual)'), ('MTech', 'MTech'), ('PGPEX-VLM', 'PGPEX-VLM'), ('PhD', 'PhD'), ('PhD(Dual)', 'PhD(Dual)'), ('Prep.', 'Prep.'), ('SURGE', 'SURGE')], default='B.Tech', max_length=7),
        ),
    ]
