# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomi', '0151_auto_20170830_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='brief_desc',
        ),
        migrations.AddField(
            model_name='groupnomination',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
